"""The classification pipeline: one function, three tiers, honest accounting.

This is the file to read first. `classify_one` is the whole routing decision in
about 30 lines, and everything else here is bookkeeping around it.
"""

from __future__ import annotations

import datetime as _dt
import time

from .config import SEVERITY, UNKNOWN
from .incidents import group_into_incidents, parse_timestamp
from .llm_classifier import LLMUnavailable, classify_with_llm
from .ml_classifier import classify_with_ml
from .regex_classifier import classify_with_regex

# ---------------------------------------------------------------------------
# Cost table
# ---------------------------------------------------------------------------
#
# Why bother computing cost at all: it is the only number that justifies the
# three-tier design. "81% of lines resolved by regex" is a claim; "$0.011 versus
# $4.20" is the argument.
#
# Prices are per million tokens in USD, keyed by model name rather than hardcoded
# as constants. That is not tidiness -- it is correctness. This table was
# originally written with the Llama-3.3-70b rates and left as bare constants,
# which meant that when the deployed model changed to qwen3.8-27b the reported
# costs silently carried the wrong price. The number this project exists to
# defend must not be the one number that can rot unnoticed.
#
# `DEFAULT_PRICE` is the fallback for any model not listed here. It is used
# deliberately rather than raising, because a mispriced cost is a reporting bug
# and must never take down a batch that classified successfully.
#
# Verify against https://console.groq.com/docs/models before quoting figures.
# Groq changes pricing without a code change, and the honest way to present
# these numbers is as "estimates at current published rates", not as invoices.
# ---------------------------------------------------------------------------

MODEL_PRICES: dict[str, tuple[float, float]] = {
    # model name: (USD per 1M input tokens, USD per 1M output tokens)
    #
    # These were wrong before. The table claimed qwen/qwen3.8-27b cost
    # $0.10/$0.30 per 1M tokens; Groq's published rate is $0.80/$4.00 — an
    # 8x understatement on input and 13x on output. Every "cost avoided"
    # figure derived from this table was therefore too small, which is the
    # exact failure this project exists to prevent: a plausible-looking wrong
    # number that nothing catches, because nothing failed.
    #
    # Rates verified against https://console.groq.com/docs/models, 2026-10-02.
    "qwen/qwen3.8-27b": (0.80, 4.00),
    "openai/gpt-oss-120b": (0.15, 0.60),
    "openai/gpt-oss-20b": (0.075, 0.30),
    # Llama-3.3-70b is retired. Kept so a report generated by an old
    # deployment stays reproducible; it no longer returns responses, and it
    # is never charged — an unreachable model costs nothing.
    "llama-3.3-70b-versatile": (0.59, 0.79),
}

# Used when the deployed model is not in the table above. This is deliberately
# the most expensive live rate rather than the cheapest: an unknown model must
# never make the cost estimate look better than it is.
DEFAULT_PRICE: tuple[float, float] = (0.80, 4.00)

CHARS_PER_TOKEN = 4

# The system prompt is ~300 tokens (measured: 1,197 characters at roughly
# 4 characters per token). Charged on every LLM call regardless of how short
# the log line is, which is why per-call cost has a floor.
#
# This is a character-based approximation rather than a real tokenisation. No
# tokenizer library is installed, and adding one (tiktoken or transformers)
# purely to compute a number that only needs to be right to within ~20% would
# be a bad trade. The prompt length is measured rather than hardcoded so the
# estimate cannot silently drift when the prompt is edited --
# `tests/test_cost.py` asserts this stays current.
SYSTEM_PROMPT_TOKENS_FALLBACK = 300


def _system_prompt_tokens() -> int:
    """Approximate the system prompt's token count.

    Imported lazily and inside a function because `pipeline` is imported by
    `llm_classifier`'s callers, and a module-level import here would be
    circular.
    """
    try:
        from .llm_classifier import SYSTEM_PROMPT

        return len(SYSTEM_PROMPT) // CHARS_PER_TOKEN
    except Exception:
        # Should not happen in normal use, but a cost estimate is never worth
        # failing a classification over.
        return SYSTEM_PROMPT_TOKENS_FALLBACK

# Output is capped at 20 tokens and the models return a short category name, so
# this is a close estimate rather than a guess.
TYPICAL_OUTPUT_TOKENS = 6


def _price_for(model: str) -> tuple[float, float]:
    """Return (input, output) price per million tokens for a model name."""
    return MODEL_PRICES.get(model, DEFAULT_PRICE)


def estimate_llm_cost(
    text: str, output_tokens: int = TYPICAL_OUTPUT_TOKENS, model: str | None = None
) -> float:
    """Estimate the USD cost of one LLM classification call.

    The token counts are approximations: a token averages about four characters
    across English text, and the system prompt is counted as a flat constant
    rather than tokenised. That is good enough for an order-of-magnitude
    comparison between tiers, which is what this number is for -- not a billing
    reconciliation.

    Why model is a parameter and not a global: the caller already knows which
    model answered, and threading it through keeps the estimate attached to the
    answer it describes instead of to whatever happens to be deployed later.
    """
    from .llm_classifier import _model_name

    input_price, output_price = _price_for(model or _model_name())
    input_tokens = len(text) // CHARS_PER_TOKEN + _system_prompt_tokens()
    return round(
        input_tokens / 1_000_000 * input_price
        + output_tokens / 1_000_000 * output_price,
        9,
    )


def classify_one(text: str, allow_llm: bool = True) -> dict:
    """Classify a single log line, trying tiers cheapest-first.

    The routing rule, and the whole idea of the project:

        regex  -- free, microseconds, catches template lines
          |
          no match
          v
        ml     -- free, milliseconds, catches unfamiliar phrasing
          |
          under 0.60 confidence
          v
        llm    -- costs money, ~300ms, catches everything else

    Returns a dict with ``category``, ``severity``, ``tier_used``,
    ``confidence``, ``latency_ms``, ``estimated_cost_usd``, and ``matched``
    (the regex rule that fired, when it was regex).

    ``allow_llm=False`` forces the pipeline to stop at the ML tier and return
    Unknown. That exists so the test suite and the offline demo can prove the
    cheaper tiers work on their own, and so an operator can run the whole system
    with no API key configured and still get a usable result.

    Why the LLM failure path returns Unknown instead of raising: a batch of
    4,000 lines should not fail because one provider call timed out. Degrading to
    Unknown with a reason attached is honest -- Unknown really is what we know --
    and it keeps the batch running.
    """
    started = time.perf_counter()
    result: dict = {"text": text, "matched": None, "note": None}

    # --- Tier 1: regex ---
    category, matched_pattern = classify_with_regex(text)
    if category:
        elapsed = (time.perf_counter() - started) * 1000
        return {
            **result,
            "category": category,
            "severity": SEVERITY.get(category, "info"),
            "tier_used": "regex",
            "confidence": 1.0,
            "matched": matched_pattern,
            "latency_ms": round(elapsed, 3),
            # Zero, not "small". This is the point of the tier.
            "estimated_cost_usd": 0.0,
        }

    # --- Tier 2: ML ---
    ml_category, confidence = classify_with_ml(text)
    if ml_category:
        elapsed = (time.perf_counter() - started) * 1000
        return {
            **result,
            "category": ml_category,
            "severity": SEVERITY.get(ml_category, "info"),
            "tier_used": "ml",
            "confidence": round(confidence, 4),
            "latency_ms": round(elapsed, 3),
            "estimated_cost_usd": 0.0,
        }

    # --- Tier 3: LLM ---
    # Reached only when both cheaper tiers abstained. When the model has not
    # been trained, this is also where every unmatched line lands, so the
    # note explains which of the two reasons applied.
    if not allow_llm:
        elapsed = (time.perf_counter() - started) * 1000
        return {
            **result,
            "category": UNKNOWN,
            "severity": SEVERITY[UNKNOWN],
            "tier_used": "unknown",
            "confidence": round(confidence, 4) if confidence else None,
            "latency_ms": round(elapsed, 3),
            "estimated_cost_usd": 0.0,
            "note": "LLM tier disabled and both cheaper tiers abstained",
        }

    try:
        llm_result = classify_with_llm(text)
        category = llm_result["category"]
        # Cost is estimated with the model that actually answered, not the
        # currently-deployed default, so a per-line figure always describes the
        # answer sitting next to it.
        cost = estimate_llm_cost(text, model=llm_result.get("model"))
        elapsed = (time.perf_counter() - started) * 1000
        return {
            **result,
            "category": category,
            "severity": SEVERITY.get(category, "info"),
            "tier_used": "llm",
            # The LLM does not return a calibrated probability, so confidence is
            # deliberately null rather than a made-up number. Reporting 0.95
            # because the model sounded sure would be a lie that shows up later
            # in a threshold comparison.
            "confidence": None,
            "raw_reply": llm_result["raw_reply"],
            "model": llm_result.get("model"),
            "latency_ms": round(elapsed, 3),
            "estimated_cost_usd": cost,
        }
    except LLMUnavailable as exc:
        elapsed = (time.perf_counter() - started) * 1000
        return {
            **result,
            "category": UNKNOWN,
            "severity": SEVERITY[UNKNOWN],
            "tier_used": "llm",
            "confidence": None,
            "latency_ms": round(elapsed, 3),
            "estimated_cost_usd": 0.0,
            "note": f"LLM unavailable, classified as Unknown: {exc}",
        }


def _normalize_input(text: str, timestamp: str | None) -> tuple[str, str | None]:
    """Return a correctly-ordered ``(text, timestamp)`` pair.

    The public API takes ``(text, timestamp)`` pairs, and a caller who passes
    them the other way round would otherwise get a system that appears to work
    while classifying every timestamp string as an unrecognisable log line and
    returning Unknown for the entire batch. That failure mode is invisible in a
    demo and obvious to a user, so it is worth detecting at the boundary.

    A first field that parses cleanly as a timestamp while the second does not
    is treated as a reversed argument pair and swapped, with the swap recorded
    in the result's note so the caller can see what happened.
    """
    if timestamp is not None and parse_timestamp(text) is not None:
        if parse_timestamp(timestamp) is None:
            return timestamp, text
    return text, timestamp


def classify_batch(
    lines: list[tuple[str, str | None]], allow_llm: bool = True
) -> dict:
    """Classify many lines and return a full triage summary.

    ``lines`` is a list of ``(text, timestamp)`` pairs. Timestamps are optional
    and are only used for incident grouping -- a single-line classification does
    not need one.

    Returns tier counts, cost, latency percentiles, per-category breakdowns, the
    grouped incidents, and the naive all-LLM cost for comparison.

    Why latency percentiles rather than just the mean: the mean hides the LLM
    tail. A batch where 96% of lines take 0.4ms and 4% take 900ms has a mean
    around 36ms and a p99 of 900, and only the percentile tells you that. The
    p50/p95/p99 split is what makes the tiering visible.
    """
    started_at = _dt.datetime.now()
    classifications = []
    fallback_happened = False
    swapped_inputs = 0

    for text, timestamp in lines:
        text, timestamp = _normalize_input(text, timestamp)
        if timestamp is not None and parse_timestamp(text) is None:
            swapped_inputs += 1
        row = classify_one(text, allow_llm=allow_llm)
        row["timestamp"] = timestamp
        row["logged_at"] = started_at.isoformat()
        # `note` is None when there is nothing to report, so it is checked
        # explicitly rather than defaulted to "". A regex-tier classification
        # returns note=None, and calling .startswith() on that crashes the whole
        # batch -- which is why the original version of this loop only ever ran
        # against lines that reached the LLM tier.
        if (row.get("note") or "").startswith("LLM unavailable"):
            fallback_happened = True
        classifications.append(row)

    total = len(classifications) or 1

    tier_counts: dict[str, int] = {}
    category_counts: dict[str, int] = {}
    latencies: list[float] = []
    total_cost = 0.0

    for row in classifications:
        tier_counts[row["tier_used"]] = tier_counts.get(row["tier_used"], 0) + 1
        category_counts[row["category"]] = category_counts.get(row["category"], 0) + 1
        latencies.append(row["latency_ms"])
        total_cost += row["estimated_cost_usd"]

    latencies.sort()

    def percentile(fraction: float) -> float:
        """Nearest-rank percentile.

        Deliberately simple rather than interpolating: with a few thousand
        samples the difference is noise, and an interpolated percentile can
        report a number that was never actually observed.
        """
        if not latencies:
            return 0.0
        index = min(len(latencies) - 1, int(round(fraction * (len(latencies) - 1))))
        return round(latencies[index], 3)

    actual_cost = round(total_cost, 6)
    naive_cost = round(
        sum(
            estimate_llm_cost(text)
            for text, _ in lines
        ),
        6,
    )

    return {
        "started_at": started_at.isoformat(),
        "total_lines": len(classifications),
        "tier_counts": tier_counts,
        "category_counts": category_counts,
        "llm_fallback": fallback_happened,
        # Non-zero when input rows arrived as (timestamp, text) and were
        # corrected. Surfaced so a caller who made that mistake finds out.
        "swapped_inputs": swapped_inputs,
        "total_cost_usd": actual_cost,
        # The number that justifies the architecture. Shown as "0x% saved" in the
        # UI, and 100% when the LLM tier never ran.
        "naive_llm_cost_usd": naive_cost,
        "cost_avoided_usd": round(max(naive_cost - actual_cost, 0.0), 6),
        "cost_avoided_pct": round((1 - actual_cost / naive_cost) * 100, 2)
        if naive_cost
        else 100.0,
        "latency_ms": {
            "p50": percentile(0.50),
            "p95": percentile(0.95),
            "p99": percentile(0.99),
            "mean": round(sum(latencies) / total, 3) if classifications else 0.0,
        },
        "classifications": classifications,
        "incidents": group_into_incidents(classifications),
    }
